port: 8888
socks-port: 8889
mixed-port: 8899
allow-lan: true
mode: rule
# ipv6: true
log-level: info
external-controller: 127.0.0.1:7174
secret: biggbon
external-ui: ./ui

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

geo-auto-update: false
geo-update-interval: 168

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  # ipv6: true
  listen: :1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - "lens.l.google.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - "*.mcdn.bilivideo.cn"
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver-policy:
    "geosite:cn,private":
      - https://1.12.12.12/dns-query
      - https://223.5.5.5/dns-query
  nameserver:
    - 'tls://8.8.4.4#MOFiSH'
    - 'tls://1.0.0.1#MOFiSH'
  proxy-server-nameserver:
    - https://1.12.12.12/dns-query

proxies:
  - name: "WARP"
    type: wireguard
    private-key: 
    peers:
      - server: engage.cloudflareclient.com
        port: 2408
        ip: 172.16.0.2
        ipv6: 2606:4700:110:8100:8895:b862:b5fa:b0cf    
        public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
        allowed-ips: ['0.0.0.0/0']
        reserved: [53,152,86]
    udp: true    
    mtu: 1280
    dialer-proxy: "AirForce"
    remote-dns-resolve: true
    dns: [1.1.1.1, 8.8.8.8]

proxy-providers:
  Airport:
    type: http
    url: 
    interval: 86400
    path: ./Airport/List.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

  HK:
    type: file
    path: ./Airport/List.yaml
    filter: 香港|Hong|HK
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

  TW:
    type: file
    path: ./Airport/List.yaml
    filter: 台湾|Taiwan|TW
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

  SG:
    type: file
    path: ./Airport/List.yaml
    filter: 新加坡|狮城|Singapore|SG
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

  JP:
    type: file
    path: ./Airport/List.yaml
    filter: 日本|Japan|JP
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

  US:
    type: file
    path: ./Airport/List.yaml
    filter: 美国|States|US
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

proxy-groups:
  - name: 🍀 Proxy
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP

  - name: 📲 Telegram
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP

  - name: 🤖 OpenAi
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP

  - name: 📹 YouTube
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP

  - name: 📺 Bahamut
    type: select
    proxies:
      - Taiwan
      - AirForce
      - WARP

  - name: 🌍 Streaming
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP
      - DIRECT

  - name: 📢 GoogleFCM
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP
      - DIRECT

  - name: 🐟 Final
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce
      - WARP
      - DIRECT

  - name: "MOFiSH"
    type: select
    proxies:
      - HongKong
      - Taiwan
      - Singapore
      - Japan
      - UnitedStates
      - AirForce

  - name: "AirForce"
    type: select
    use:
      - Airport
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 600

  - name: "HongKong"
    type: select
    use:
      - HK
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 600

  - name: "Taiwan"
    type: select
    use:
      - TW
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 600

  - name: "Singapore"
    type: select
    use:
      - SG
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 600

  - name: "Japan"
    type: select
    use:
      - JP
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 600

  - name: "UnitedStates"
    type: select
    use:
      - US
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 600

rule-providers:
  GoogleFCM:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
    path: ./ACL4SSR/GoogleFCM.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml"
    path: ./ACL4SSR/Telegram.yaml
    interval: 86400

  ProxyMedia:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml"
    path: ./ACL4SSR/ProxyMedia.yaml
    interval: 86400

rules:
  - DOMAIN,gac-geo.googlecnapps.cn,DIRECT
  - DOMAIN-SUFFIX,uttjhu.xyz,DIRECT
  - DOMAIN-SUFFIX,emby.wtf,🌍 Streaming
  - DOMAIN-SUFFIX,jmsooo.com,🌍 Streaming
  - DOMAIN-SUFFIX,pornemby.club,🌍 Streaming
  - GEOSITE,private,DIRECT
  - RULE-SET,GoogleFCM,📢 GoogleFCM
  - RULE-SET,Telegram,📲 Telegram
  - GEOSITE,openai,🤖 OpenAi
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,bahamut,📺 Bahamut
  - RULE-SET,ProxyMedia,🌍 Streaming
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,🍀 Proxy
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,🐟 Final